package cn.com.pubtoinfo.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SendMsgToPortType", targetNamespace = "http://service.pubinfo.com.cn")
public interface SendMsgToPortType {

	/**
	 * 
	 * @param in2
	 * @param in1
	 * @param in4
	 * @param in3
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.pubinfo.com.cn")
	@RequestWrapper(localName = "sendMsgTo", targetNamespace = "http://service.pubinfo.com.cn", className = "cn.com.pubtoinfo.service.SendMsgTo")
	@ResponseWrapper(localName = "sendMsgToResponse", targetNamespace = "http://service.pubinfo.com.cn", className = "cn.com.pubtoinfo.service.SendMsgToResponse")
	public String sendMsgTo(
            @WebParam(name = "in0", targetNamespace = "http://service.pubinfo.com.cn") String in0,
            @WebParam(name = "in1", targetNamespace = "http://service.pubinfo.com.cn") String in1,
            @WebParam(name = "in2", targetNamespace = "http://service.pubinfo.com.cn") String in2,
            @WebParam(name = "in3", targetNamespace = "http://service.pubinfo.com.cn") String in3,
            @WebParam(name = "in4", targetNamespace = "http://service.pubinfo.com.cn") String in4);

}
