server:
  port: 8081
  tomcat:
    accept-count: 200  #tomcat接受排队的最大数量
    max-connections: 2000 #tomcat处理的最大连接数
    connection-timeout: 5000
    threads:
      max: 1000 #tomcat工作线程数量
      min-spare: 100 # 最小工作空闲线程数，默认10。（适当增大一些，以便应对突然增长的访问量）

eureka:
  instance:
    prefer-ip-address: true
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: ${eureka_host:http://localhost:8761/eureka}
    fetch-registry: false
    register-with-eureka: true
#debug: true

spring:
  application:
    name: auditserver
  flyway:
    baseline-on-migrate: true
    enabled: true
    encoding: UTF-8
    validate-on-migrate: false
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  redis:
    database: 0 #Redis索引0~15，默认为0
    host: ${redis_host:localhost}
    port: ${redis_port:6379}
    password: ${redis_password:123456}
    lettuce: # 这里标明使用lettuce配置
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接
    timeout: 10000ms    #连接超时时间（毫秒）
  kafka:
    bootstrap-servers: ${boot_strap_servers:127.0.0.1:9092} #kafka地址配置
    consumer:
      group-id: ${consumer_group_id:localhost_auditserver} #用户组
      auto-startup: ${consumer_auto_startup:true} #启动项目时是否需要启动本地kafka

#elk日志系统
logstash:
  destination: ${ls_dest:localhost}
  appname: ${ls_name:default}

datasource:
  projectName: ${project_name:auditserver}                            # 该参数必须与redis中大仪的键值相对应，否则读取不到数据库信息
  enableExecuteFlywayOnMultiDatasource: true          # 是否同步flyway到多数据源下的其它数据库，默认true
  schoolName: ${school_name:limsproduct}              # 该参数用于动态读取学校静态资源(logo图片等)，必须与redis多数据源设置中的schoolName参数保持一致
  strictMode: ${datasource_strict_mode:true}

