package cn.com.pubinfo.service;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * SendMsg service = new SendMsg();
 * SendMsgPortType portType = service.getSendMsgHttpPort();
 * portType.sendMsg(...);
 * </pre>
 * 
 * </p>
 * 
 */
// http://{阿里云消息服务}:8080/gxtMsgService/services/SendMsg?wsdl
@WebServiceClient(name = "SendMsg", targetNamespace = "http://service.pubinfo.com.cn", wsdlLocation = "http://localhost:8080/gxtMsgService/services/SendMsg?wsdl")
public class SendMsg_Service extends Service {

	private final static URL SENDMSG_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(cn.com.pubinfo.service.SendMsg_Service.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = cn.com.pubinfo.service.SendMsg_Service.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/gxtMsgService/services/SendMsg?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/gxtMsgService/services/SendMsg?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SENDMSG_WSDL_LOCATION = url;
	}

	public SendMsg_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SendMsg_Service() {
		super(SENDMSG_WSDL_LOCATION, new QName("http://service.pubinfo.com.cn",
				"SendMsg"));
	}

	/**
	 * 
	 * @return returns SendMsgPortType
	 */
	@WebEndpoint(name = "SendMsgHttpPort")
	public SendMsgPortType getSendMsgHttpPort() {
		return super.getPort(new QName("http://service.pubinfo.com.cn",
				"SendMsgHttpPort"), SendMsgPortType.class);
	}

}
