server:
  port: 8760
spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
    encoding: UTF-8
    validate-on-migrate: false
  application:
    name: ZUUL-SERVICE
  datasource:
    url: jdbc:mysql://${db_host:localhost}/${db_name:zuul}?useUnilocalhostcode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: ${db_user:root}
    password: ${db_pwd:0822}
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90 # 过期时间
    lease-renewal-interval-in-seconds: 30 # 续约时间
  client:
    serviceUrl:
      defaultZone: ${eureka_host:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: '*'


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: ${timeout_in_milliseconds:120000}
ribbon:
  ReadTimeout: ${read_timeout:20000}
  ConnectTimeout: ${connect_timeout:20000}

zuul:
  sensitive-headers:
  ignored-headers: